language: python

python:
  - "2.7"

install:
  - pip install pytest

script:
  - py.test

after_success:
  - env
  - |
    if [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BRANCH" == "master" ]
    then
      if [ "$TRAVIS_TAG" != "" ] && [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
      then
        revs=( ${TRAVIS_TAG//./ } )
        echo docker push example/test:${revs[0]}.${revs[1]}.${revs[2]}
        echo docker push example/test:${revs[0]}.${revs[1]}
        echo docker push example/test:${revs[0]}
      fi
    fi
